### PR TITLE
Always remember what channels and patterns are subscribed

### PR DESCRIPTION
**Pull request by kichik**
The user is expecting the channel to be subscribed as soon as the method returns
If the connection breaks after dispatching the command but before getting the confirmation, this may not happen

### CODE REVIEW

**Comment by kichik** [comment]
I have been thinking about it some more, and there are more corner cases where we may end up with forgotten channels. Specifically when trying to subscribe while in that state of "half-connected" that the SSL tunnel provides. But even without it, if the connection dies at the exact right time after the command was sent but before the response was received, a channel might end up being forgotten.

This change is a bit of an overkill, especially with the concurrent hash sets for thread safety. But in my use case, it's going to help ensure subscriptions are not lost. What do you think?

**Comment by mp911de** [comment]
Thanks for your PR. The proposed change breaks lettuce's style. These information are stored for the connection only after receiving a successful confirmation. Other examples are `auth(password)` and `select(databasenumber)`. 

I would like rather a way of overriding certain components to allow specific changes by users of lettuce. 
For example, a way to extend the `RedisAsyncConnectionImpl` class or `RedisPubSubConnectionImpl` so you can use add your changes and receive all the callbacks. This way lettuce stays clean but allows to change behavior specific to particular implementations/environments. 

This is for a longer time on my mind. Basically it would mean, to extract the producer methods of `RedisPubSubConnectionImpl` and `RedisAsyncConnectionImpl` in the regular and the cluster client.

Users could then subclass RedisClient and the respective class so they can add own behavior. A slightly different approach would be providing a sort of factory where RedisClient obtains its connection classes from, but I currently do not have an idea how to achieve this without affecting all instances of `RedisClient` (a non-static way).

**Comment by kichik** [comment]
I understand this might be not be Lettuce style, but this leaves an open issue. When I call `subscribe()` I can never tell if it succeeded or not. Since there is no return value and no access to internal connection state, I have to assume it succeeded. But in fact it may fail silently if the connection dies at the right time or, in my case, if the SSL tunnel is up but Redis is down for upgrade. It will successfully connect, possibly try to send the command exactly once and then just forget about it (`CommandHandler.channelActive()` clears `commandBuffer` and tries writing exactly once but may fail after the first command and forget about the others).

Ideally `subscribe()` and friends would return a future so I can tell when it failed and simply try again. However `RedisPubSubConnectionImpl` has a much simpler interface right now and I was trying to keep it this way with this commit. If you'd rather go the future route, or have a better idea, I'm up for it.

**Comment by mp911de** [comment]
I like the idea of a future as result. This approach will align the PubSub API style with the lettuce API style. I created #34 which handles the API extension. 

In addition to that, you're able to extend `RedisPubSubConnectionImpl` and do fancy stuff as you need.
Is it ok with you to close this issue in favor of #34 ?

**Comment by kichik** [comment]
Sure, this can be closed.

**Comment by kichik** [comment]
We tried using the new futures returned from `subscribe()` but even those don't solve the problem completely. The issue I mentioned before with `CommandHandler.channelActive()` is still there. If there is an exception in the bottom loop that rewrites the commands, the rest of the commands in `tmp` get ignored and their future is never cancelled or completed.

We are using a custom implementation of `RedisPubSubConnectionImpl` for now using your new API and it's working fine. I'll try to submit a pull request for the remaining issue. The simplest solution seem s to be just cancelling the rest of the commands if one fails.

**Comment by mp911de** [comment]
Do you mean something like the following code?

```java
List<RedisCommand<K, V, ?>> processedCommands = new ArrayList<RedisCommand<K, V, ?>>(tmp.size());
        try {
            for (RedisCommand<K, V, ?> cmd : tmp) {
                if (!cmd.isCancelled()) {

                    if (logger.isDebugEnabled()) {
                        logger.debug("[" + this + "] channelActive() triggering command " + cmd);
                    }
                    ctx.channel().writeAndFlush(cmd);
                }
                processedCommands.add(cmd);
            }
        } catch (Exception e) {
            tmp.removeAll(processedCommands);
            for (RedisCommand<K, V, ?> cmd : tmp) {
                if (!cmd.isCancelled()) {
                    cmd.setException(new RedisConnectionException("Cannot re-submit command while activating the connection", e));
                    cmd.cancel(true);
                }
                processedCommands.add(cmd);
            }
        }
        finally {
            tmp.removeAll(processedCommands);
            for (RedisCommand<K, V, ?> cmd : tmp) {
                if (!cmd.isCancelled()) {
                    cmd.setException(new RedisConnectionException("Cannot re-submit command while activating the connection"));
                    cmd.cancel(true);
                }
            }
        }
```

I guess, the cancelling part has to take also exceptions in `redisChannelHandler.activated()` into account, so the snippet above is just a draft.

**Comment by kichik** [comment]
Yes, that was the basic idea. There may be other places that need this
treatment. I didn't get a chance to dig further after finding this one.

**Comment by kichik** [comment]
So even after fixing this issue, there is still a possibility to lose subscriptions without notification. The futures generated in `activate()` are not accessible. Additionally, that same method fails if there are too many subscriptions due to Redis buffer limits. We had to implement buffered resubscription where the buffer is limited to 59k channels.

**Comment by mp911de** [comment]
So, any further proposals on how to deal with the issue? There are for sure recoverable and non-recoverable errors, `activate()` should not loose anything.

**Comment by kichik** [comment]
What we're using right now is my original proposal plus a few extra measures to verify the subscriptions and fix the issues I just mentioned and the deadlock issue I just opened. I don't have a solution that stays inline with current lettuce style. I don't see a way around having lettuce be a bit more autonomous here. Maybe an extra listener that reports the results of futures in `activated()`? It might get clumsy. The user will have to hold a list of expected subscriptions and see if the one that failed is still required.

**Pull request closed without merging**
