### PR TITLE
Expose ByteBufAllocator in ClientResources

### PR DESCRIPTION
**Pull request by jwils**
To have more control over buffer allocation configuration, it would be
nice to include the option to choose what allocator to use.

### CODE REVIEW

**Comment by mp911de** [comment]
Hi @jwils thanks for the PR. The code looks pretty decent. Could you help me understand your motivation for the change? Could this issue be solved by switching to `ByteBufAllocator.DEFAULT`?

**Comment by jwils** [comment]
If including netty from lettuce as a shaded jar it'll have to use a different PooledAllocator than other netty instance. The default allocator is configured to use up to 50% of memory so two or more instances can cause problem. 

I can use the system properties to set each size if you want to minimize the parameters for ClientResources.

**Comment by mp911de** [comment]
Having a solution outside `ClientResources` would be my preferred solution. Using the shaded jar comes with several drawbacks and imposes constraints on applications. Reuse of netty resources (allocators, event loops) is no longer possible.

**Comment by mp911de** [comment]
Closing this PR for now.

**Pull request closed without merging**
