### PR TITLE
Fix sync/async/reactive methods for thread-safe

### PR DESCRIPTION
**Pull request by jongyeol**
I found bugs related with thread safety in `*ConnectionImpl`s. So, I fixed sync/async/reactive methods of `*ConnectionImpl`s' using double checked locking.

Refers:
- https://en.wikipedia.org/wiki/Double-checked_locking#Usage_in_Java
- http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html

Make sure that:

- [x] You have read the [contribution guidelines](https://github.com/mp911de/lettuce/blob/master/.github/CONTRIBUTING.md).
- [x] You use the code formatters provided [here](https://github.com/mp911de/lettuce/blob/master/formatting.xml) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.

### CODE REVIEW

**Comment by jongyeol** [comment]
@mp911de , There are no `netty-41next` profile in `pom.xml` and using ssl were failed in CI. But, `make test` was passed in local (mac os x). I think this test failures are not related with this PR.
So, Anyway, Could you review this PR?

**Comment by mp911de** [comment]
Thanks for the PR. I fixed the profile in the TravisCI config. I think we could even perform eager initialization of the API wrapper objects and making these `final`. API wrappers are lightweight objects, they even though they construct a command builder.

**Comment by jongyeol** [comment]
@mp911de , I think you're worrying about `volatile`'s performance decrement. Isn't it? Then, did you mean this style?

(via https://en.wikipedia.org/wiki/Double-checked_locking#Usage_in_Java)
```java
public class FinalWrapper<T> {
    public final T value;
    public FinalWrapper(T value) {
        this.value = value;
    }
}

public class Foo {
   private FinalWrapper<Helper> helperWrapper;

   public Helper getHelper() {
      FinalWrapper<Helper> wrapper = helperWrapper;

      if (wrapper == null) {
          synchronized(this) {
              if (helperWrapper == null) {
                  helperWrapper = new FinalWrapper<Helper>(new Helper());
              }
              wrapper = helperWrapper;
          }
      }
      return wrapper.value;
   }
}
```

In this, if we use `final` for `helperWrapper` with eager initialization like follow codes. Then, `public final T value` must be `volatile` like `AtomicReference`'s implementation. Or, CPUs' L1,L2 will be different.
(refer: https://github.com/openjdk-mirror/jdk7u-jdk/blob/f4d80957e89a19a29bb9f9807d2a28351ed7f7df/src/share/classes/java/util/concurrent/atomic/AtomicReference.java#L60)

```java
public class FinalWrapper<T> {
    private volatile T value; // this must be volatile in this case.
    public FinalWrapper(T value) { this.value = value; }
    public void set(T value) { this.value = value; }
    public T get() { return value; }
}

public class Foo {
   private final FinalWrapper<Helper> helperWrapper = new FinalWrapper<>(null);
   ...
}
```

I think we cannot use `final` for API wrapper instance and avoiding `volatile` together. If you didn't mean this, could you explain about it more?

**Comment by mp911de** [comment]
Thanks for your detailed response. I'm not worried about `volatile`. The code here isn't on the critical path, `sync()`/`async()`/`reactive()` isn't something you usually call on each command invocation. 
There are other places (like `CommandHandler`) that make heavy use of `volatile` and that maybe could need optimization as `CommandHandler` is involved in each command invocation.

Seeing all that effort about synchronization and lazy initialization make me think whether lazy initialization is really needed and I came to the conclusion, that it's not. Therefore, I'd perform the initialization right in the constructor.

**Comment by jongyeol** [comment]
I see. Well then, may I change sync/async/reactive to eager initialization in constructors?

**Comment by jongyeol** [comment]
@mp911de , I updated this PR with eager initialization of sync/async/reactive. Could you review this?

**Comment by mp911de** [comment]
Thanks a lot. It looks good, going to merge the PR in the next days.

**Comment by mp911de** [comment]
That's merged and polished with fd7dcc63564580fdb0a6ef9cb3d3e464b7de21a8.

**Pull request closed without merging**
