### PR TITLE
Ping before connect

### PR DESCRIPTION
**Pull request by mp911de**

### CODE REVIEW

**Comment by mp911de** [comment]
@kichik Basic support for PING before connect/reconnect is available within this PR. What do you expect from this feature? In you SSL tunnel case the connection won't be simply activated.

**Comment by kichik** [comment]
Yes, this is perfect. Thanks! `cancelCommandsOnReconnectFailure` will be very helpful too. Just to be sure, it will keep retrying if ping fails, right?

**Comment by mp911de** [comment]
No, it stops. 

Reconnecting has two phases. First is the open connection requests leads to an established TCP connection. Failures in this phase cause always retries on failure. Phase 2 is a higher level of connection validation. The second phase came through SSL. If errors occur here (for example SSL host verification fails, PING before fails) the reconnect stops. I guess, this is again a point where users would like to take control.

I'l  add another option like `stopReconnectOnConnectionValidationFailures` but I need a better name first.

**Comment by kichik** [comment]
This may be a problem with existing connections. If the initial connection is fully successful and disconnects a few days later for a minute, what happens? Currently it will just retry until it's connected again. But if the tunnel is up and Redis is down, ping will fail. If that closes the connection completely, how can I know about it? We may need a listener for that, or ideally, let it keep trying in this case.

For the first connection option, maybe `mustConenctSuccessfullyOnce`?

**Comment by mp911de** [comment]
Until now, if a connection is in a "broken" state the next issued command would fail with something like

```
java.util.concurrent.ExecutionException: com.lambdaworks.redis.RedisException: Invalid first byte: 84
	at com.lambdaworks.redis.protocol.Command.get(Command.java:140)
	at com.lambdaworks.redis.ClientTest.pingBeforeConnectFailOnReconnect(ClientTest.java:153)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
Caused by: com.lambdaworks.redis.RedisException: Invalid first byte: 84
	at com.lambdaworks.redis.protocol.RedisStateMachine.readReplyType(RedisStateMachine.java:195)
```

With `ClientOptions` I added `autoReconnect` that can be set to `false`. So if the connection gets disconnected, the user will get as well an exception. Both exceptions are transported within the future. 

I want to state with that, both connections behave in the same way, if auto reconnection is not possible, the future completes with an exception. I will add the option to retry reconnects even if there are errors.

**Comment by kichik** [comment]
But what if there are no commands and the connection is used for pubsub? There is no future that can fail.

**Comment by mp911de** [comment]
Sync and async connections provide `isOpen()` for those who are interested whether the connection is currently connected. And there is [RedisConnectionStateListener](http://redis.paluch.biz/apidocs/com/lambdaworks/redis/RedisConnectionStateListener.html). If you have very special use cases or want to do some magic, these features should help you.

**Comment by kichik** [comment]
I'm still debating with myself whether or not this is a special use case. Feel free to solve this dilemma for me at any time by saying it is. I basically expect the watchdog to make sure my connection is always up and since there are no explicit reconnect notifications, I expect it to maintain my pubsub subscriptions. I think the new ping feature, as it is now, makes this harder, not easier.

The problem with `RedisConnectionStateListener` is that it is invoked even if the watchdog isn't disabled by the ping activator. So I'd have to sleep, see if the connection is brought back up or not and then open my own. Or most likely, I'd just have to disable the connection watchdog and do the reconnection myself. And if I reconnect myself, then it's back to the same issue of having to hold double subscription lists as I'd have to resubscribe myself too. It would be nice if the watchdog and ping could work together so that once the connection is already verified, ping won't disable it, but only have the watchdog reconnect.

Another possibility, if you prefer to keep this as is, would be to add another to `RedisConnectionStateListener` called `onWatchdogDone` or something similar.

BTW I had a little trouble building latest lettuce. It seems like some Java 8 features are used but `pom.xml` still requires 1.6. Specifically `CommandType` has `import jdk.nashorn.internal.ir.PropertyKey;` and some classes use `FunctionalInterface`.

**Comment by mp911de** [comment]
I'll have to take some time to think about the issue. 

In the mean time: lettuce needs Java 8 to be built but stays usable with Java 6 and 7. `@FunctionalInterface` is missing in earlier JDK's, the nature of annotations allows this approach. I created https://github.com/mp911de/lettuce-testcontainer to verify compatibility on Java 6 and 7.

**Comment by kichik** [comment]
Shouldn't `<source>` be 1.8 in `maven-compiler-plugin` so Maven build fails without the right JDK? If `<target>` stays the same it should still be usable in Java 6.

**Comment by mp911de** [comment]
If `<source>` is `1.8`, then `<target>` is required to be `1.8` as well

```
$ lettuce mark$ javac -source 1.8 -target 1.6 src/main/java/com/lambdaworks/codec/CRC16.java 
javac: source release 1.8 requires target release 1.8
```

**Comment by mp911de** [comment]
Your case has to be covered by the regular operations. Reconnects ought to be transparent for lettuce users. 

I took a while to think about the issue and came to the conclusion, to flip the behavior of the connection watchdogs when it runs on an error. 

The expectation is that reconnects will occur indefinitely, but there are certain cases in which you might want to turn off that behavior. I assumed the stop reconnected behavior on errors as default that does not fit the overall expectation.

Users would have the possibility to stop reconnect if `PING` or SSL host verification fails but that would not be a default case. 

I'm currently not sure, whether the `PING` before connect will solve your problem, at least the way it is working now. As far as I understood, the problem you have is, the SSL tunnel holds some data, and the tunnel sends the data to the client as soon as the client connects. 
So submitting data through the tunnel and waiting for the `PING` reply just adds more gibberish to the communication line. The communication line is out of sync with the protocol and response bytes are not where they are expected, right?

**Comment by kichik** [comment]
Thanks, I'm glad we can agree on the use case.

`PING` doesn't help solve the problem you described, but it helps with something else. If the tunnel is up but Redis is down (upgrade, etc.) then `PING` will make sure no queued commands are sent through this dead channel and get lost for no reason. Along with other improvements, this can help more easily maintain a consistent list of subscriptions.

**Comment by kichik** [comment]
Thanks!

**Comment by mp911de** [comment]
@kichik @taer I would like to release lettuce 3.2.Beta1 tomorrow. Can you give it a test then?

**Comment by kichik** [comment]
Ping seems to work as advertised on 3.2.Beta1. Thanks. 

I did have issues testing on Windows because of the new Unix domain sockets. I can't create an instance of RedisUri without faking DomainSocketAddress class. Maybe have that dynamically loaded somehow?

**Comment by mp911de** [comment]
Thanks for your feedback. I'll have a look.

**Comment by mp911de** [comment]
I dressed the missing class issue with #64

**Pull request merged**
